version: "3.11"
x-build: &build
  build: .
x-env: &env
  environment:
    - PORT=${PORT}
    - WASABI_ACCESS_KEY=${WASABI_ACCESS_KEY}
    - WASABI_SECRET_KEY=${WASABI_SECRET_KEY}
    - WASABI_REGION=${WASABI_REGION}
    - S3_BUCKET=${S3_BUCKET}
    - S3_TEST_BUCKET=${S3_TEST_BUCKET}
    - SENTRY_DSN=${SENTRY_DSN}
x-test: &test
  volumes:
    - ./test-results:/app/test-results
  profiles:
    - testing
services:
  web:
    <<: [*build, *env]
    command: gunicorn -w 4 'vectorizing:create_app()' --timeout 0 -b 0.0.0.0:$PORT --log-level debug
    ports:
      - ${PORT}:${PORT}