name: deploy

on:
  push:
    branches:
      - production
      - main
      - 
jobs:
  deploy-py-server-argo:
    name: Deploy PY server Argo
    uses: ./.github/workflows/helpers-deploy-argo.yaml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      WASABI_ACCESS_KEY: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_WASABI_ACCESS_KEY || secrets.STAGING_WASABI_ACCESS_KEY }}
      WASABI_SECRET_KEY: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_WASABI_SECRET_KEY || secrets.STAGING_WASABI_SECRET_KEY }}
      WASABI_REGION: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_WASABI_REGION || secrets.STAGING_WASABI_REGION }}
